apiVersion: v1
kind: PersistentVolume
metadata:
  name: hls-data
  namespace: rmtp
spec:
  storageClassName: "nfs-medium"
  capacity:
    storage: 990Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /hlsdata
    server: 10.210.28.130
                               
