apiVersion: v1
kind: PersistentVolume
metadata:
  name: hls-data
  namespace: rmtp
spec:
  storageClassName: "nfs-medium"
  capacity:
    storage: 950Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /hls_data
    server: 10.23.11.250
