apiVersion: v1
kind: PersistentVolume
metadata:
  name: hls-data
  namespace: rmtp
spec:
  storageClassName: local
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nas-data/hls-data"
