apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-relay
  namespace: rmtp
data:
  nginx.conf: |
      worker_processes auto;
      rtmp_auto_push on;
      events {}
      rtmp {
          server {
              listen 1935;
              listen [::]:1935 ipv6only=on;

              application streamout {
                  live on;
                  record off;
              }
          }
      }
